### ISSUE TITLE
Consider making dune the default executable name or fall back to it

### ISSUE THREAD

**Issue by zploskey** [maelvls/vscode-dune#1]
The dune name change has been in a for while now. It would be nice not to have to override the `dune.path` setting to use it. What do you think?

**Comment by maelvls** [comment]
Hi! Thanks for the feedback. I’ll take a look ASAP 🙂

**Comment by maelvls** [comment]
I just realized I'm not even calling `dune` at all; I had made an attempt (with `dune.path` and stuff) but didn't get the time to finish it. That's why there is still no linting 😞

**Comment by zploskey** [comment]
Ah, well it is nice to at least have basic syntax highlighting for now. It's worth switching the default setting even if you're not calling it yet because nearly every new user will get an error popping up saying it can't find the dune executable. Thanks for looking into this.

**Comment by maelvls** [comment]
Thank you so much for reporting this, I didn't even pay attention to this issue. I'll disable that check for now... Sorry for the delay

**Comment by maelvls** [comment]
Btw, I just noticed they introduced a linter mode to dune (https://github.com/ocaml/dune/issues/351 and mentioned in https://github.com/ocaml/dune/issues/1201):

    dune build @lint

Now I think I could add the linter feature 😀

**Comment by maelvls** [comment]
I just released the 0.0.4 version, the message shouldn't appear anymore.

I'll try to implement a proper linting asap
