### ISSUE TITLE
Comment syntax is wrong?

### ISSUE THREAD

**Issue by anmonteiro** [maelvls/vscode-dune#4]
Dune doesn't understand comments of the form `#;`. I would suggest always toggling comments with `;`.

**Comment by maelvls** [comment]
Excellent suggestion, thank you! 😊 


Would you like to try and propose a PR? If you want,
the file to edit is there: https://github.com/maelvalais/vscode-dune/blob/master/dune.configuration.json

**Comment by anmonteiro** [comment]
Sure, opened https://github.com/maelvalais/vscode-dune/pull/5
